# Generated by Django 2.2.7 on 2019-11-21 08:12
from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path
from django.conf import settings
from django.conf.urls.static import static

DATA_FILENAME = 'data.json'


def load_data(apps, schema_editor):
    Pothole = apps.get_model('potholes', 'Pothole')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    #img=tags.get('image',0)
                    location = fromstr(
                        f'POINT({longitude} {latitude})', srid=4326
                    )
                    Pothole(name=name, location=location).save()
            except KeyError:
                pass

class Migration(migrations.Migration):
    dependencies = [
        ('potholes', '0001_initial'),
    ]
    operations = [migrations.RunPython(load_data)
    ]
